### ISSUE TITLE
Tests can hang in com.walmartlabs.lacinia.async-test on CI server

### ISSUE THREAD

**Issue by hlship** [walmartlabs/lacinia#100]
See build https://circleci.com/gh/walmartlabs/lacinia/287

Looks like tests can hang in com.walmartlabs.lacinia.async-test; we should introduce necessary timeouts to fail the tests fast (CircleCI gives up after 10 minutes).

**Comment by yuanbohan** [comment]
Sometimes I encounter the dead lock issue with `lein test` command, and it will hang without any output, but it will succeed most of the time. I am sorry that I did not find anything useful to solve this issue. 

Need help, The following the jstack content:

```
jstack 72207
2017-10-24 10:07:06
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode):

"Attach Listener" #19 daemon prio=9 os_prio=31 tid=0x00007f96fa1de800 nid=0x5007 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"ClosingPipeCloser 1395073533" #18 daemon prio=5 os_prio=31 tid=0x00007f96fb16a000 nid=0x5a03 in Object.wait() [0x000070000c938000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	- locked <0x000000076b5ff1d0> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hypirion.io.Pipe.join(Pipe.java:120)
	at com.hypirion.io.ClosingPipe$OutCloser.run(ClosingPipe.java:111)
	at java.lang.Thread.run(Thread.java:745)

"PipeThread 1395073533" #17 daemon prio=5 os_prio=31 tid=0x00007f96f99fe800 nid=0x5803 in Object.wait() [0x000070000c835000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at com.hypirion.io.RevivableInputStream.read(RevivableInputStream.java:140)
	- locked <0x000000076b5b97d0> (a java.lang.Object)
	- locked <0x000000076b5b96f8> (a com.hypirion.io.RevivableInputStream)
	at java.io.InputStream.read(InputStream.java:101)
	at com.hypirion.io.Pipe$PipeOutputStream.run(Pipe.java:239)
	at java.lang.Thread.run(Thread.java:745)

"PipeThread 2032647583" #16 daemon prio=5 os_prio=31 tid=0x00007f96fab23800 nid=0x5603 runnable [0x000070000c732000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x000000076b5f65f0> (a java.lang.UNIXProcess$ProcessPipeInputStream)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.hypirion.io.Pipe$PipeOutputStream.run(Pipe.java:239)
	at java.lang.Thread.run(Thread.java:745)

"PipeThread 1934692470" #15 daemon prio=5 os_prio=31 tid=0x00007f96fab22800 nid=0x5403 runnable [0x000070000c62f000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x000000076b5f4530> (a java.lang.UNIXProcess$ProcessPipeInputStream)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.hypirion.io.Pipe$PipeOutputStream.run(Pipe.java:239)
	at java.lang.Thread.run(Thread.java:745)

"RevivableReader 461516748" #13 daemon prio=5 os_prio=31 tid=0x00007f96fab22000 nid=0x5203 runnable [0x000070000c52c000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:233)
	at com.hypirion.io.RevivableInputStream$ThreadReader.run(RevivableInputStream.java:232)
	at java.lang.Thread.run(Thread.java:745)

"process reaper" #10 daemon prio=10 os_prio=31 tid=0x00007f96fa1e2000 nid=0x4c03 runnable [0x000070000c223000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.UNIXProcess.waitForProcessExit(Native Method)
	at java.lang.UNIXProcess.lambda$initStreams$266(UNIXProcess.java:290)
	at java.lang.UNIXProcess$$Lambda$7/282496973.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x00007f96fa86a800 nid=0x4803 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007f96fa878800 nid=0x4603 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007f96fa878000 nid=0x4403 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007f96fa830000 nid=0x4203 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007f96fa82f000 nid=0x400b runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007f96fa00a800 nid=0x3303 in Object.wait() [0x000070000bbe6000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c00102c8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007f96fa00a000 nid=0x3103 in Object.wait() [0x000070000bae3000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x00000006c0011ed8> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=31 tid=0x00007f96fb004000 nid=0x1b03 in Object.wait() [0x000070000b4ca000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	- locked <0x000000076b5fcec0> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hypirion.io.Pipe.join(Pipe.java:120)
	at leiningen.core.eval$sh.invokeStatic(eval.clj:199)
	at leiningen.core.eval$sh.doInvoke(eval.clj:181)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.eval$fn__5625.invokeStatic(eval.clj:269)
	at leiningen.core.eval$fn__5625.invoke(eval.clj:267)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:373)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:363)
	at leiningen.test$test.invokeStatic(test.clj:196)
	at leiningen.test$test.doInvoke(test.clj:163)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$partial_task$fn__5829.doInvoke(main.clj:272)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$apply_task.invokeStatic(main.clj:322)
	at leiningen.core.main$apply_task.invoke(main.clj:308)
	at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:328)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:324)
	at leiningen.core.main$_main$fn__5895.invoke(main.clj:401)
	at leiningen.core.main$_main.invokeStatic(main.clj:394)
	at leiningen.core.main$_main.doInvoke(main.clj:391)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.main$main_opt.invokeStatic(main.clj:314)
	at clojure.main$main_opt.invoke(main.clj:310)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at clojure.lang.Var.invoke(Var.java:388)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)

"VM Thread" os_prio=31 tid=0x00007f96fa859800 nid=0x2f03 runnable

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007f96fa002800 nid=0x2707 runnable

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007f96fa808800 nid=0x2903 runnable

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007f96fa809800 nid=0x2b03 runnable

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007f96fa80a000 nid=0x2d03 runnable

"VM Periodic Task Thread" os_prio=31 tid=0x00007f96fa86b000 nid=0x4a03 waiting on condition

JNI global references: 231
```

**Comment by hlship** [comment]
Haven't seen this in quite some time.
