### ISSUE TITLE
Possible race condition 

### ISSUE THREAD

**Issue by manute** [walmartlabs/lacinia#223]
Hi , 

I'm using the lacinia version `0.28.0` and an async wrapper for the field resolver 

```clojure
(defn wrap-resolver-async [f]
  (fn [& args]
    (let [promise (resolve/resolve-promise)]
      (async/go
        (try
          (resolve/deliver! promise (apply f args))
          (catch Exception e
            (log/errorf e "caught an exception in function: %s" f)
            (resolve/deliver! promise nil (as-error-map e {:forValue (last args)})))))
      promise)))
```
It's being used in the `attach-resolvers` like 
```clojure
:resolve-in-config    (wrap-resolver-async (partial resolve-fn service-api))
```

I think it is related with #197 because anytime there's an exception in that func I encounter this  
```
Exception in thread "async-dispatch-4" 
java.lang.IllegalStateException: May only realize a ResolverResultPromise once.
	at com.walmartlabs.lacinia.resolve$resolve_promise$reify__17483.deliver_BANG_(resolve.clj:173)
	at com.walmartlabs.lacinia.resolve$resolve_promise$reify__17483.deliver_BANG_(resolve.clj:186)
	at repoql.util$wrap_resolver_async$fn__23899$fn__23907$state_machine__9247__auto____23914$fn__23916$fn__23918.invoke(util.clj:49)
	at repoql.util$wrap_resolver_async$fn__23899$fn__23907$state_machine__9247__auto____23914$fn__23916.invoke(util.clj:45)
	at repoql.util$wrap_resolver_async$fn__23899$fn__23907$state_machine__9247__auto____23914.invoke(util.clj:44)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at repoql.util$wrap_resolver_async$fn__23899$fn__23907.invoke(util.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Thanks in advance!

**Comment by hlship** [comment]
I know someone else identified a race condition in this code and I thought it was already fixed.  Let me check on that.

**Comment by hlship** [comment]
It was supposed to be fixed by 62da37cd04353884a0a9d024402c3d2b80b3306d (part of 0.28.0) ...

That's very odd; I can't see anything that would cause the deliver! to be invoked twice.

**Comment by hlship** [comment]
Could you:

* Try it with 0.29.0 (nothing should have changed, however)
* Change from async/go to async/thread to see if that makes a difference

**Comment by hlship** [comment]
The new code really is simpler ... something must be invoking `deliver!` twice; are you sure it's not something else in your code?  A breakpoint might help, though I've had bad luck with breakpoints inside reify-ed methods.

**Comment by manute** [comment]
Hi Howard, thanks for your response. 

Unfortunately with `thread` instead of `go` didn't change the scenario, also we can not move to `0.29.0` yet. 

Finally what we did to fix that issue was this : 

```clojure
(defn throw-err [e]
  (when (instance? Throwable e) (throw e))
  e)

(defmacro <? [ch]
  `(throw-err (async/<! ~ch)))

(defn get-data-async [f args]
  (async/go
    (try
      (apply f args)
      (catch Exception e
        e))))

(defn wrap-resolver-async [f]
  (fn [& args]
    (let [promise (resolve/resolve-promise)]
      (async/go
        (try
          (let [data (<? (get-data-async f args))]
            (log/debugf "data async: %s" data)
            (resolve/deliver! promise data))
          (catch Exception e
            (log/errorf e "caught an exception in function: %s" f)
            (resolve/deliver! promise nil (ex->graphql-error e {:forValue (last args)})))))
      promise)))
```

I know is not the best solution, but it works so we are fine now. 
Closing this. 
Thanks again.
