### ISSUE TITLE
Bug when loading Lacinia

### ISSUE THREAD

**Issue by ghivert** [walmartlabs/lacinia#229]
Hi!

I'm trying to use lacinia in my project, but got (when using `lein repl`):

```
Caused by: java.io.FileNotFoundException: Could not locate com/walmartlabs/lacinia/lacinia__init.class or com/walmartlabs/lacinia/lacinia.clj on classpath.
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval13$loading__6434__auto____14.invoke(user.clj:1)
	at user$eval13.invokeStatic(user.clj:1)
	at user$eval13.invoke(user.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
        ... 6 more
```

Searching through the jar, apparently, the structure is:

```
com/
  walmartlabs/
    lacinia/
    lacinia.clj
```

So the file would be `com/walmartlabs/lacinia.clj` and not `com/walmartlabs/lacinia/lacinia.clj`.

Is this normal? Did I do something wrong?

**Comment by ghivert** [comment]
Well, this was mainly an error from my side, when setting requires in Clojure (pretty new to Clojure for me...)
Sorry for the post. 🙂
