### ISSUE TITLE
Custom scalars break in 0.31.0-RC1

### ISSUE THREAD

**Issue by priyatam** [walmartlabs/lacinia#255]
When upgraded from 0.30.0 to 0.31.0-RC1 the following error is thrown on compiling schema:

```
Arguments to compile do not conform to spec:
#object[clojure.spec.alpha$spec_impl$reify__2059 0xe3eb13a "clojure.spec.alpha$spec_impl$reify__2059@e3eb13a"] - failed: (not (spec? %)) in: [0 :scalars :Datetime 1 :parse] at: [:schema :scalars 1 :parse] spec: :com.walmartlabs.lacinia.schema/not-a-conformer
#object[clojure.spec.alpha$spec_impl$reify__2059 0x2f991b05 "clojure.spec.alpha$spec_impl$reify__2059@2f991b05"] - failed: (not (spec? %)) in: [0 :scalars :Datetime 1 :serialize] at: [:schema :scalars 1 :serialize] spec: :com.walmartlabs.lacinia.schema/not-a-conformer

	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3707)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:368)
	at clojure.lang.RT.maybeLoadResourceScript(RT.java:364)
	at clojure.lang.RT.doInit(RT.java:485)
	at clojure.lang.RT.<clinit>(RT.java:338)
```

schema:
```
 :scalars
 {:Datetime
  {:parse :parse-datetime
   :serialize :serialize-datetime}}

```
code
```
(def parse-datetime
  (schema/as-conformer (fn [^String v]
                         (ZonedDateTime/parse v))))

(def serialize-datetime
  (schema/as-conformer (fn [^ZonedDateTime v]
                         (.format v DateTimeFormatter/ISO_DATE_TIME))))

(defn load-schema
  [component]
  (-> (io/resource "schema.edn")
      slurp
      edn/read-string
      (util/attach-scalar-transformers
        {:parse-datetime parse-datetime
         :serialize-datetime serialize-datetime})
      (util/attach-resolvers (resolver-map component))
      schema/compile))
```

**Comment by kgann** [comment]
This is due to https://github.com/walmartlabs/lacinia/pull/246

See https://github.com/walmartlabs/lacinia/blob/master/CHANGES.md#breaking-change-incompatible-changes-to-scalars

**Comment by hlship** [comment]
I'd like to slap at 1.0 on the version number, but until then, minor breaking changes may still happen.
