### ISSUE TITLE
Can't start with Clojure 1.9

### ISSUE THREAD

**Issue by wilkerlucio** [walmartlabs/lacinia#27]
Hello, I tried to start a new project with Lacinia and Clojure 1.9, when trying to run the REPL I always get this error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2183)
	at clojure.lang.RT.classForName(RT.java:2192)
	at clojure.lang.RT.loadClassForName(RT.java:2211)
	at clojure.lang.RT.load(RT.java:445)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.lang.RT.doInit(RT.java:463)
	at clojure.lang.RT.<clinit>(RT.java:333)
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: import in this context, compiling:(clojure/core_instant18.clj:11:1)
	at clojure.lang.Compiler.analyze(Compiler.java:6720)
	at clojure.lang.Compiler.analyze(Compiler.java:6657)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3767)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6921)
	at clojure.lang.Compiler.analyze(Compiler.java:6701)
	at clojure.lang.Compiler.analyze(Compiler.java:6657)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6030)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5407)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3973)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6917)
	at clojure.lang.Compiler.analyze(Compiler.java:6701)
	at clojure.lang.Compiler.eval(Compiler.java:6975)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7831.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$fn__9320.invokeStatic(core.clj:6664)
	at clojure.core$fn__9320.invoke(core.clj:6662)
	at clojure.core__init.load(Unknown Source)
	at clojure.core__init.<clinit>(Unknown Source)
	... 10 more
Caused by: java.lang.RuntimeException: Unable to resolve symbol: import in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7215)
	at clojure.lang.Compiler.resolve(Compiler.java:7159)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7120)
	at clojure.lang.Compiler.analyze(Compiler.java:6680)
	... 34 more
Exception in thread "Thread-3" clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at leiningen.core.eval$fn__5732.invokeStatic(eval.clj:264)
	at leiningen.core.eval$fn__5732.invoke(eval.clj:260)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:366)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:356)
	at leiningen.repl$server$fn__11838.invoke(repl.clj:243)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
```

I tried with Clojure 1.9.0-alpha14 and 1.9.0-alpha15.

It works fine with Clojure 1.8.0.

**Comment by bcarrell** [comment]
You're absolutely right; looking into a fix for this now.

**Comment by ura1a** [comment]
`[com.walmartlabs/lacinia "0.14.0" :exclusions [clojure-future-spec]]` works for me with Clojure 1.9.0-alpha14

**Comment by bcarrell** [comment]
Ha, okay, it looks like we already solved it in the docs.  Close this if you're happy.

**Comment by wilkerlucio** [comment]
Ah, ok, I didn't found on the docs when I was reading it, maybe we can add this information on the main README?

**Comment by bcarrell** [comment]
Added a note to the README.  Closing this; open a new issue if you have more questions!
