### ISSUE TITLE
Unable to resolve symbol import with clojure 1.9

### ISSUE THREAD

**Issue by tvanhens** [walmartlabs/lacinia#46]
I am unable to depend on lacinia with clojure 1.9.0-x.

`project.clj`
```
(defproject server "0.1.0-SNAPSHOT"
  :description "Backend api for the snap-battle system."
  :url "http://api.snapbattle.com"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0-alpha15"]

                 [com.walmartlabs/lacinia "0.15.0"]
                 ]
  )

```

Stacktrace
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2183)
	at clojure.lang.RT.classForName(RT.java:2192)
	at clojure.lang.RT.loadClassForName(RT.java:2211)
	at clojure.lang.RT.load(RT.java:445)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.lang.RT.doInit(RT.java:463)
	at clojure.lang.RT.<clinit>(RT.java:333)
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: import in this context, compiling:(clojure/core_instant18.clj:11:1)
	at clojure.lang.Compiler.analyze(Compiler.java:6720)
	at clojure.lang.Compiler.analyze(Compiler.java:6657)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3767)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6921)
	at clojure.lang.Compiler.analyze(Compiler.java:6701)
	at clojure.lang.Compiler.analyze(Compiler.java:6657)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6030)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5407)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3973)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6917)
	at clojure.lang.Compiler.analyze(Compiler.java:6701)
	at clojure.lang.Compiler.eval(Compiler.java:6975)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7831.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$fn__9320.invokeStatic(core.clj:6664)
	at clojure.core$fn__9320.invoke(core.clj:6662)
	at clojure.core__init.load(Unknown Source)
	at clojure.core__init.<clinit>(Unknown Source)
	... 10 more
Caused by: java.lang.RuntimeException: Unable to resolve symbol: import in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7215)
	at clojure.lang.Compiler.resolve(Compiler.java:7159)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7120)
	at clojure.lang.Compiler.analyze(Compiler.java:6680)
	... 34 more
Subprocess failed
```

**Comment by kgann** [comment]
You need to exclude clojure-future-spec --
https://github.com/walmartlabs/lacinia/blob/master/README.md#status

On Apr 22, 2017 7:13 PM, "Tyler van Hensbergen" <notifications@github.com>
wrote:

I am unable to depend on lacinia with clojure 1.9.0-x.

project.clj

(defproject server "0.1.0-SNAPSHOT"
  :description "Backend api for the snap-battle system."
  :url "http://api.snapbattle.com"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0-alpha15"]

                 [com.walmartlabs/lacinia "0.15.0"]
                 ]
  )


Stacktrace

Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2183)
	at clojure.lang.RT.classForName(RT.java:2192)
	at clojure.lang.RT.loadClassForName(RT.java:2211)
	at clojure.lang.RT.load(RT.java:445)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.lang.RT.doInit(RT.java:463)
	at clojure.lang.RT.<clinit>(RT.java:333)
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.RuntimeException: Unable to resolve symbol:
import in this context, compiling:(clojure/core_instant18.clj:11:1)
	at clojure.lang.Compiler.analyze(Compiler.java:6720)
	at clojure.lang.Compiler.analyze(Compiler.java:6657)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3767)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6921)
	at clojure.lang.Compiler.analyze(Compiler.java:6701)
	at clojure.lang.Compiler.analyze(Compiler.java:6657)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6030)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5407)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3973)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6917)
	at clojure.lang.Compiler.analyze(Compiler.java:6701)
	at clojure.lang.Compiler.eval(Compiler.java:6975)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7831.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$fn__9320.invokeStatic(core.clj:6664)
	at clojure.core$fn__9320.invoke(core.clj:6662)
	at clojure.core__init.load(Unknown Source)
	at clojure.core__init.<clinit>(Unknown Source)
	... 10 more
Caused by: java.lang.RuntimeException: Unable to resolve symbol:
import in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7215)
	at clojure.lang.Compiler.resolve(Compiler.java:7159)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7120)
	at clojure.lang.Compiler.analyze(Compiler.java:6680)
	... 34 more
Subprocess failed

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/walmartlabs/lacinia/issues/46>, or mute the thread

**Comment by tvanhens** [comment]
Apologies. Didn't catch that. Thanks!
